### ISSUE TITLE
Errors on startup with new Configuration model

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispersservices#391]
I checked out notifications branch and when I ran `python manage.py runserver` I got the following errors:

```
(venv) BL-UITS-RTLT021:whispersservices_django machrist$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "whispers_configuration" does not exist
LINE 1: ...on"."name", "whispers_configuration"."value" FROM "whispers_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/core/management/base.py", line 387, in check
    all_issues = self._run_checks(
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/whispersservices_django/urls.py", line 22, in <module>
    path('', include('whispersservices.urls')),
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/whispersservices/urls.py", line 5, in <module>
    from whispersservices import views
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/whispersservices/views.py", line 18, in <module>
    from whispersservices.serializers import *
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/whispersservices/serializers.py", line 21, in <module>
    GEONAMES_USERNAME = Configuration.objects.filter(name='geonames_username').first().value
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/machrist/SGCI/WHISPers/whispersservices_django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "whispers_configuration" does not exist
LINE 1: ...on"."name", "whispers_configuration"."value" FROM "whispers_...
                                                             ^
```

The problem is that my database doesn't yet have the Configuration migrations, but I'm neither able to start the Django server nor am I able to run `python manage.py migrate`. I think the problem is that these Configuration queries are run on import in serializers.py and views.py.

I worked around this by commenting out the problem lines:
- https://github.com/USGS-WiM/whispersservices_django/blob/notifications/whispersservices/serializers.py#L21-L27
- https://github.com/USGS-WiM/whispersservices_django/blob/notifications/whispersservices/views.py#L58-L60

Then I was able to start the server and also able to run `migrate`.

Another problem I also ran into is that when I uncommented the lines listed above, since I didn't have any Configuration records yet, those lines of code failed. Perhaps the code could be changed to use a default if the Configuration record is missing, or a migration could create a default set of Configuration records?

**Comment by machristie** [comment]
This should be fixed now by #446
