### ISSUE TITLE
Debug Custom Notification Error When Using 'AND' Operator in Species Diagnosis Field

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/whispersservices#516]
Traceback:

```
[2021-09-20 15:17:02,288: ERROR/MainProcess] Task whispersapi.scheduled_tasks.custom_notifications_by_user[5
eff218f-8779-4255-a080-46e718dfef8a] raised unexpected: ProgrammingError('column "whispers_event.created_dat
e" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT DISTINCT "whispers
_event"."id", "whispers_event"."cre...\n                                               ^\n')
Traceback (most recent call last):
  File "c:\projects\whispersservices\venv\lib\site-packages\django\db\backends\utils.py",
line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.GroupingError: column "whispers_event.created_date" must appear in the GROUP BY clause or be
 used in an aggregate function
LINE 1: SELECT DISTINCT "whispers_event"."id", "whispers_event"."cre...
                                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\projects\whispersservices\venv\lib\site-packages\celery\app\trace.py", line 405
, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\projects\whispersservices\venv\lib\site-packages\celery\app\trace.py", line 697
, in __protected_call__
    return self.run(*args, **kwargs)
  File "C:\projects\whispersservices\whispersapi\scheduled_tasks.py", line 1251, in custom
_notifications_by_user
    queryset, criteria = build_custom_notifications_query(cue, base_queryset)
  File "C:\projects\whispersservices\whispersapi\scheduled_tasks.py", line 1221, in build_
custom_notifications_query
    for item in queryset:


django.db.utils.ProgrammingError: column "whispers_event.created_date" must appear in the GROUP BY clause or
 be used in an aggregate function
LINE 1: SELECT DISTINCT "whispers_event"."id", "whispers_event"."cre...
```

This seems to be the offending query:

```
queryset = queryset.annotate(count_diagnoses=Count(
                    'eventlocations__locationspecies__speciesdiagnoses__diagnosis', distinct=True)).filter(
                    count_diagnoses__gte=len(values))
```

**Comment by aaronstephenson** [comment]
Fixed in 1ffc437c.

Solution was to use separate queryset that only selects event the ID column, then use the resulting list of IDs to filter the main queryset.

Note that this problem also occurred on the admin level one and species criteria in the custom notifications code, so I applied the same solution to those.
